# use env from parent SConstruct
Import('env')

# lexer
env.Object('lexer.o', 'lexer.cc')
env.Object('lexer_test.o', 'lexer_test.cc')
env.Program('lexer_test', ['lexer_test.o', 'lexer.o'])

# parser
env.Object('parser.o', 'parser.cc')
env.Object('parser_test.o', 'parser_test.cc')
env.Program('parser_test', ['parser_test.o', 'lexer.o', 'parser.o'])

# symbol table
env.Object('symbol_table.o', 'symbol_table.cc')
env.Object('symbol_table_test.o', 'symbol_table_test.cc')
env.Program('symbol_table_test', ['symbol_table_test.o', 'symbol_table.o', 'parser.o', 'lexer.o'])

# # interpreter
# env.Object('interpreter.o', 'interpreter.cc')
# env.Object('main.o', 'interpreter_main.cc')
# env.Program('interpreter', ['main.o', 'interpreter.o', 'lexer.o', 'parser.o'])



