env = Environment(CXXFLAGS = '-std=c++20')

# compile main.cc to main.o
env.Object('main.o', 'main.cc')

# compile interpreter.cc to interpreter.o
env.Object('interpreter.o', 'interpreter.cc')
env.Object('lexer.o', 'lexer.cc')

# link main.o and interpreter.o to executable as interpreter
env.Program('interpreter', ['main.o', 'interpreter.o', 'lexer.o'])